= End-2-End Testing mit Playwright Java
Frederik Hahne (adesso SE) <frederik.hahne@adesso.de>
v1.0, 2024-01-15: Rohentwurf

// Die folgenden Attribute darfst Du NICHT verändern:
:doctype: article
:table-caption: Tabelle
:listing-caption: Listing
:figure-caption: Abbildung
:source-language: java
:source-indent: no
:source-highlighter: rouge
:xrefstyle: short
:reproducible:

// Die folgenden Attribute darfst Du gerne anpassen:
:imagesdir: .

[abstract]
Während in letzter Zeit „Fullstack“ Entwicklung mit Java und Server-Side-Rendering wieder mehr
in Mode gekommen ist muss man für End-2-End Tests entweder auf Javascript-basierte Frameworks zurückgreifen
oder Selenium verwenden, mit allen Vor- und Nachteilen.
In diesem Artikel werden wir Playwright Java <<Playwright-Website>> als moderne Alternative zur
Browserautomatisierung und End-2-End Testing vorstellen,
sodass jeglicher Code mit Java geschrieben werden kann.

== Playwright Java im Überblick

Playwright ist eine von Microsoft entwickelte open-source Bibliothek zur Browserautomatisierung und end-2-end Testing.
Playwright unterstützt verschiedene Browser und übernimmt auch die Installation auf jeder unterstützten Platform (Windows, Mac, Linux).
Es existieren Implementierungen für TypeScript, JavaScript, Python, .NET und Java, wobei die Implementierung für Node.js die führende Variante ist.
Eine Reihe von Tools erleichtert sowohl das Erstellen von Test als auch die Fehlersuche.
Mithilfe des Codegen Tools können Klickpfade aufgezeichnet werden und in jeder unterstützten Sprache abgespeichert werden.
Der Inspector erlaubt es Test schrittweise zu durchlaufen und dabei z.B. Locator ändern.
Mit dem Trace-Viewer <<Playwright-Trace-Viewer>> kann man die Timeline eines ausgeführten Tests betrachten und somit im Fehlerfall das Problem identifizieren.
Playwright verspricht, dass "flaky" Tests der Vergangenheit angehören unter anderem durch Auto-wait <<Playwright-Auto-Wait>> und automatischen Retries, sodass keine künstlichen Timeouts oder Wartezeiten in Tests eingebaut werden müssen.
Neben Browsertests kann Playwright auch verwendet werden, um REST Apis zu testen, diesen Anwendungsfall werden wir hier nicht näher betrachten.
Es ist ebenfalls möglich Anfragen und Antworten abzufangen und zu verändern um zum Beispiel das Verhalten der Anwendung im Fehlerfall zu prüfen.

== Playwright ohne Test Runner

== Playwright mit JUnit

== Ausblick

== Fazit


[bibliography]
== Quellen

- [[[Playwright-Website,1]]] Playwright Website: link:https://playwright.dev/java//[]
- [[[JavaAktuell,2]]] Frederik Hahne (2023): Java Aktuell 1/23, Moderne Frontends mit Thymeleaf, Spring Boot und HTMX
- [[[Playwright-Trace-Viewer,3]]] Playwright Trace-Viewer: link:https://playwright.dev/java/docs/trace-viewer-intro[]
- [[[Playwright-Auto-Wait,4]]] Auto-waiting Dokumentation: link:https://playwright.dev/java/docs/actionability[]


== Über den Autoren/die Autorin

Frederik entwickelt seit 2007 vorwiegend Webanwendungen, er besitzt aber auch Erfahrung im Bau von Desktopanwendungen,
angefangen von JSP-basierten Anwendungen über Wicket bis hin zu Angular und Vue.

Seit 2022 bringt Frederik sein Wissen als Senior Software Engineer für die adesso SE am wunderschönen Standort Paderborn
in verschiedene, meist Java-basierte Projekte ein.
In der knappen freien Zeit organisiert er die Java User Group Paderborn, um
den Wissensaustausch, nicht nur zum Thema Java, in und um Paderborn zu fördern.

Er ist seit 2015 teil des JHipster Core Teams und kümmert sich dort insbesondere um den Gradle Support.